[project]
name = "fractalize"
version = "0.1.0"
description = "Fire Simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.0",
    "matplotlib>=3.10.8",
    "numba>=0.63.1",
    "numpy>=2.3.5",
    "uvicorn[standard]>=0.40.0",
]
